
/*<auto-generated>
***End of Global definition area***
Changes to this comment may cause incorrect behavior during document based import.
</auto-generated>*/

export function MyNewFunction() {
    // This one is edit in VSCode and import in TIA Portal 
    // with add-in JSConnector
    HMIRuntime.Trace("Hello TIA Portal !");
}
